name: Publish
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: '9.5.0'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 20

      - name: Build
        run: |
          pnpm install
          pnpm build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
